CONVENIOS = [{"id":1,"convenio":"ALLIANZ SAÚDE"},
                {"id":2,"convenio":"AMEPLAN SAÚDE"},
                {"id":3,"convenio":"AMIL FACIL"},
                {"id":4,"convenio":"AMIL SAÚDE"},
                {"id":5,"convenio":"BIOSAÚDE"},
                {"id":6,"convenio":"BIOVIDA SAÚDE"},
                {"id":7,"convenio":"BLUE MED SAÚDE"},
                {"id":8,"convenio":"BRADESCO SAÚDE"},
                {"id":9,"convenio":"CLASSES LABORIOSAS"},
                {"id":10,"convenio":"CRUZ AZUL SAÚDE"},
                {"id":11,"convenio":"GS SAÚDE"},
                {"id":12,"convenio":"GOLDEN CROSS"},
                {"id":13,"convenio":"HAPVIDA"},
                {"id":14,"convenio":"HEALTH SANTARIS"},
                {"id":15,"convenio":"INTERCLINICAS SAÚDE"}]

PREPAROS = [{"id":1,"preparo":"A coleta de sangue deve ser realizada preferencialmente com o paciente em jejum de acordo com o exame a ser realizado"},
                {"id":2,"preparo":"4h para dosagem de prolactina recomendando-se um repouso de 30 minutos antes da coleta para quem fez exercícios físicos"},
                {"id":3,"preparo":"Após esta coleta o paciente deverá fazer uma refeição normal do seu dia a dia"},
                {"id":4,"preparo":"Realizar a coleta preferencialmente pela manhã no dia da entrega ao laboratório"},
                {"id":5,"preparo":"ta dieta deverá ser iniciada 48 horas (dois dias) antes do início da coleta do material"},
                {"id":6,"preparo":"4h para dosagem de prolactina recomendando-se um repouso de 30 minutos antes da coleta para quem fez exercícios físicos"},
                {"id":7,"preparo":"A coleta de sangue deve ser realizada preferencialmente com o paciente em jejum de acordo com o exame a ser realizado"},
                {"id":8,"preparo":"A coleta de sangue deve ser realizada preferencialmente com o paciente em jejum de acordo com o exame a ser realizado"},
                {"id":9,"preparo":"ta dieta deverá ser iniciada 48 horas (dois dias) antes do início da coleta do material"},
                {"id":10,"preparo":"Realizar a coleta preferencialmente pela manhã no dia da entrega ao laboratório"},
                {"id":11,"preparo":"Após esta coleta o paciente deverá fazer uma refeição normal do seu dia a dia"},
                {"id":12,"preparo":"ta dieta deverá ser iniciada 48 horas (dois dias) antes do início da coleta do material"},
                {"id":13,"preparo":"Após esta coleta o paciente deverá fazer uma refeição normal do seu dia a dia"},
                {"id":14,"preparo":"ta dieta deverá ser iniciada 48 horas (dois dias) antes do início da coleta do material"},
                {"id":15,"preparo":"I4h para dosagem de prolactina recomendando-se um repouso de 30 minutos antes da coleta para quem fez exercícios físicos"}]

EXAMES = [{"id":1,"exame":"Hemograma"},
            {"id":2,"exame":"Colesterol"},
            {"id":3,"exame":"Ureia e Creatinina"},
            {"id":4,"exame":"Papanicolau"},
            {"id":5,"exame":"Exames de urina"},
            {"id":6,"exame":"Exames de fezes"},
            {"id":7,"exame":"Glicemia"},
            {"id":8,"exame":"Transaminases (ALT e AST) ou TGP e TGO"},
            {"id":9,"exame":"Mamografia"},
            {"id":10,"exame":"Desintometria óssea"},
            {"id":11,"exame":"Ressonância Magnética"},
            {"id":12,"exame":"Tomografia Computadorizada"},
            {"id":13,"exame":"Ultra-sonografia"},
            {"id":14,"exame":"Ecografia tridimensional"},
            {"id":15,"exame":"Ecodopler"}]

ORCAMENTOS = [{"id":1,"valor":"$11.69"},
                {"id":2,"valor":"$167.14"},
                {"id":3,"valor":"$278.32"},
                {"id":4,"valor":"$72.66"},
                {"id":5,"valor":"$107.81"},
                {"id":6,"valor":"$377.61"},
                {"id":7,"valor":"$426.89"},
                {"id":8,"valor":"$88.78"},
                {"id":9,"valor":"$443.89"},
                {"id":10,"valor":"$90.98"},
                {"id":11,"valor":"$472.39"},
                {"id":12,"valor":"$65.19"},
                {"id":13,"valor":"$445.36"},
                {"id":14,"valor":"$45.89"},
                {"id":15,"valor":"$475.85"}]

UNIDADES = [{"id":1,"unidade":"Hoard"},
            {"id":2,"unidade":"Graedel"},
            {"id":3,"unidade":"Cherokee"},
            {"id":4,"unidade":"Lawn"}]

DATAS = [{"id":1,"data":"25-04-2021"},
        {"id":2,"data":"08-11-2021"},
        {"id":3,"data":"04-07-2022"},
        {"id":4,"data":"02-07-2022"},
        {"id":1,"data":"28-04-2022"},
        {"id":2,"data":"12-06-2022"},
        {"id":3,"data":"11-10-2022"},
        {"id":4,"data":"20-06-2022"},
        {"id":1,"data":"24-11-2022"},
        {"id":2,"data":"22-10-2021"},
        {"id":1,"data":"01-11-2021"},
        {"id":2,"data":"08-04-2022"},
        {"id":3,"data":"09-08-2022"},
        {"id":4,"data":"22-02-2022"},
        {"id":1,"data":"07-06-2021"},
        {"id":2,"data":"05-06-2021"},
        {"id":3,"data":"01-01-2022"},
        {"id":4,"data":"29-11-2022"},
        {"id":2,"data":"18-11-2021"},
        {"id":1,"data":"12-08-2022"},
        {"id":3,"data":"26-06-2021"},
        {"id":4,"data":"23-07-2022"},
        {"id":2,"data":"14-12-2022"},
        {"id":2,"data":"25-08-2021"},
        {"id":3,"data":"11-11-2022"},
        {"id":3,"data":"16-09-2021"},
        {"id":3,"data":"20-08-2022"},
        {"id":1,"data":"26-08-2021"},
        {"id":2,"data":"05-11-2021"},
        {"id":2,"data":"29-10-2021"}]